spring.application.name=teste
Spring.datasource.url=jdbc:mysql://localhost:3306/senai
Spring.datasource.username=root
Spring.datasource.password = alunolab
Spring.jpa.hibernate.ddl-auto=update
Spring.jpa.show-sql=true

sever.port=8080